version: '3.8'

services:
  anpr-api:
    build: .
    container_name: junigadi-anpr-api
    ports:
      - "8080:8080"
    volumes:
      - ./ANPR:/app/ANPR
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
